-- VIEWS IN SQL:

CREATE VIEW user_details AS
SELECT ID, NAME, EMAIL FROM USER;

Select * from user_details;



CREATE VIEW SALARY_DETAILS AS
SELECT ID,NAME, SALARY FROM SALARY_TABLE WHERE SALARY> 60000;

SELECT* FROM SALARY_DETAILS;

-- DROP tHE VIEW 

DROP VIEW USER_DETAILS;

