-- GROUP BY & HAVING: 

-- GROUP BY 

SELECT GENDER, AVG(SALARY) AS AVG_SALARY
FROM salary_table
group by GENDER;


-- USING ROLLUP WITH GROUP BY;
SELECT GENDER, AVG(SALARY) AS AVG_SALARY
FROM salary_table
group by GENDER WITH ROLLUP;





SELECT REFERRED_BY_ID , COUNT(REFERRED_BY_ID) AS TOTAL_REFERRED
FROM USER
WHERE REFERRED_BY_ID IS NOT NULL
GROUP BY REFERRED_BY_ID;


-- USING HAVING:

SELECT 
	GENDER AS 'GENDER', AVG(salary) AS 'AVG-SALARY', count(*) AS COUNT
FROM salary_table
GROUP BY GENDER
HAVING AVG(SALARY)>40000;



SELECT REFERRED_BY_ID , COUNT(REFERRED_BY_ID) AS TOTAL_REFERRED
FROM USER
WHERE REFERRED_BY_ID IS NOT NULL
GROUP BY REFERRED_BY_ID
HAVING count(*)> 1;