-- SUBQUERIES IN SQL:

-- 1ST CHECK AVG SALARY:
Select AVG(SALARY) 
	FROM SALARY_TABLE;

-- SUBQERY:
-- WE WANT TO FIND USER WHO EARN MORE THAN THE AVG SALARY?
SELECT 
	id,name,salary 
FROM salary_table
WHERE salary> (
		Select AVG(SALARY) 
	FROM SALARY_TABLE
    );


-- USING IN:
SELECT 
	ID, name
FROM USER
WHERE ID IN (
		SELECT USER_ID 
	FROM ADDRESSES
);

-- WE WANT TO FIND USERS WHO HAVE BEEN REFEERED BY SOMEONE WHO EARNS MORE THAN 40000? 

SELECT 
	ID,NAME,REFERRED_BY_ID
FROM USER
WHERE REFERRED_BY_ID IN (
        SELECT 
			ID 
		FROM salary_table
        WHERE salary> 40000
	);

